// Runtime only. Content comes from workshop.data.js (window.WORKSHOP_MODULES),
// generated by scripts/build-site.mjs from workshop/lessons/*.md. This file owns
// navigation, copy-to-clipboard, and lesson chrome — never content.

const modules = window.WORKSHOP_MODULES;

const linksHost = document.getElementById("module-links");
const content = document.getElementById("content");

linksHost.innerHTML = modules.map(module => `<button class="module-link" data-module="${module.id}"><span>${module.number}</span>${module.nav}</button>`).join("");

function showModule(id, updateHash = true) {
  if (id === "port") id = "plan";
  const module = modules.find(item => item.id === id) || modules[0];
  content.innerHTML = `<section class="module"><div class="module-head"><div><p class="step">Step ${module.number} · ${module.time}</p><h1>${module.title}</h1></div></div><p class="lead">${module.lead}</p>${lessonBrief(module)}${module.body}${lessonNavigation(module)}</section>`;
  document.querySelectorAll(".module-link").forEach(link => link.classList.toggle("active", link.dataset.module === module.id));
  document.querySelector(`.module-link[data-module="${module.id}"]`)?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });
  document.querySelectorAll(".copy").forEach(button => button.addEventListener("click", () => copyCommand(button)));
  document.querySelectorAll("[data-go-module]").forEach(button => button.addEventListener("click", () => showModule(button.dataset.goModule)));
  if (updateHash) history.replaceState(null, "", `#${module.id}`);
  document.title = `${module.nav} | Past the Vibes`;
  content.focus({ preventScroll: true });
  window.scrollTo({ top: 0, behavior: "smooth" });
}

// The copy button lives in a .command header; its command text is the adjacent
// <pre><code>. Read it straight from the DOM so there is no parallel command map.
function commandText(button) {
  const code = button.closest(".command")?.querySelector("pre code");
  return code ? code.textContent : "";
}

async function copyCommand(button) {
  const text = commandText(button);
  try {
    if (navigator.clipboard && window.isSecureContext) await navigator.clipboard.writeText(text);
    else fallbackCopy(text);
  } catch {
    fallbackCopy(text);
  }
  const toast = document.getElementById("toast");
  toast.classList.add("show");
  setTimeout(() => toast.classList.remove("show"), 1200);
}

function fallbackCopy(value) {
  const textarea = document.createElement("textarea");
  textarea.value = value;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  textarea.remove();
}

document.querySelectorAll(".module-link").forEach(link => link.addEventListener("click", () => showModule(link.dataset.module)));
showModule(location.hash.slice(1) || "welcome", false);

function lessonBrief(module) { return `<section class="lesson-brief" aria-label="Lesson goals"><div><span>By the end, you can</span><p>${module.objective}</p></div><div><span>Evidence you will produce</span><p>${module.evidence}</p></div></section>`; }
function lessonNavigation(module) {
  const index = modules.indexOf(module);
  const previous = modules[index - 1];
  const next = modules[index + 1];
  return `<nav class="lesson-nav" aria-label="Lesson navigation">${previous ? `<button data-go-module="${previous.id}"><span>Previous</span>${previous.number} · ${previous.nav}</button>` : "<span></span>"}${next ? `<button class="next" data-go-module="${next.id}"><span>Next</span>${next.number} · ${next.nav}</button>` : `<button class="next" data-go-module="welcome"><span>Review</span>Return to setup</button>`}</nav>`;
}
